import re

def assign(service, arg):
	if service == 'www':
		return True, arg

def audit(arg):
	dir_list = ['/fck/',
	'/solr/',
	'/spaw2/',
	'/typo3/',
	'/CFIDE/',
	'/admin/',
	'/forum/',
	'/files/',
	'/engine/',
	'/banner/',
	'/images/',
	'/editor/',
	'/cgi-bin/',
	'/WEB-INF/',
	'/upadmin/',
	'/control/',
	'/include/',
	'/umbraco/',
	'/Modules/',
	'/console/',
	'/manager/',
	'/install/',
	'/invoker/',
	'/webapps/',
	'/services/',
	'/concrete/',
	'/advanced/',
	'/symphony/',
	'/includes/',
	'/ckeditor/',
	'/ckfinder/',
	'/Services/',
	'/WorkArea/',
	'/wp-admin/',
	'/activeweb/',
	'/fckeditor/',
	'/fileadmin/',
	'/articlefr/',
	'/PowUpload/',
	'/SystemTab/',
	'/Providers/',
	'/Backstage/',
	'/jonasAdmin/',
	'/phpmyadmin/',
	'/management/',
	'/components/',
	'/wp-content/',
	'/WebServices/',
	'/jmx-console/',
	'/textpattern/',
	'/express_edit/',
	'/assetmanager/',
	'/UserControls/',
	'/imageLibrary/',
	'/admin-console/',
	'/administrator/',
	'/eaflashupload/',
	'/profile-upload/',
	'/axis2/axis2-admin/',
	'/page.cfm',
	'/media.cfm',
	'/moadmin.php',
	'/wp-login.php',
	'/webadmin.nsf',
	'/common/index.jsf',
	'/ibm/console/logon.jsp',
	'/IDSWebApp/IDSjsp/Login.jsp',
	'/CFIDE/administrator/index.cfm',
	'/.git/',
	'/.svn/',
	'/.bzr/',
	'/.DS_Store',
	'/.htaccess',
	'/.subversion',
	'/CVS/Entries',
	'/.svn/entries',
	'/.hg/requires',
	'/README.txt',
	'/readme.html',
	'/LICENSE.txt',
	'/CHANGELOG.txt',
	'/web.rar',
	'/web.zip',
	'/www.rar',
	'/www.zip',
	'/web.tar.gz',
	'/www.tar.gz',
	'/wwwroot.rar',
	'/wwwroot.zip',
	'/wwwroot.tar.gz',
	'/robots.txt',
	'/index.do',
	'/index.php',
	'/index.asp',
	'/index.jsp',
	'/index.cfm',
	'/index.nsf',
	'/index.aspx',
	'/index.action',
	'/test.php',
	'/phpinfo.php',
	'/index.php.swp',
	'/index.jsp.swp',
	'/default.php.swp',
	'/default.jsp.swp'
	 ]
	for path in dir_list:
		target = arg + path
		code, head, res, err, _ = curl.curl2(target)
		if code == 200:
			security_note('Web Directory discover: ' + target)
		if code == 301:
			target = re.findall(r'(?<=Location:\s)(.*?)(?=\n)',head)[0].strip()
			code, head, res, err, _ = curl.curl2(target)
			if code == 200:
				security_note('Web Directory discover: ' + target)